### ISSUE TITLE
linkml-map does not work with example

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#2216]
**Describe the bug**
Executing the transformation described in the [Basic idea](https://linkml.io/linkml-map/##basic-idea) does not work with `linkml-map@0.3.7`.

**To reproduce**
1. Install `linkml-map@0.3.7`.
2. Create a schema derived from the [LinkML tutorial](https://linkml.io/linkml/intro/tutorial01.html#your-first-schema) with the needed attributes with the right range.
3. Create the Person model provided in the linkml-map [Basic idea](https://linkml.io/linkml-map/##basic-idea) in a file with name `Person-001.yaml`. Run `linkml-validate --schema personinfo.yaml -C Person Person-001.yaml` to ensure that schema and data match each-other.
4. Create the transformation specification provided in the linkml-map [Basic idea](https://linkml.io/linkml-map/##basic-idea) in a file with name `transformation.yaml`.
5. Try to execute the transformation `linkml-map map-data -T ./transformation.yaml -s ./personinfo.yaml --source-type Person Person-001.yaml`.
6. Observe error `AttributeError: 'NoneType' object has no attribute 'ucum_code'`

**Expected behavior**

The example transformation takes place.

**About your computer (if applicable, please complete the following information):**
 - Component: linkml-map
 - Version: v0.3.7

**Additional information**

Error traceback:
```
Traceback (most recent call last):
  File "[...]/pypoetry/virtualenvs/schema-transformations-hTVHmvgu-py3.11/bin/linkml-map", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "[...]/pypoetry/virtualenvs/schema-transformations-hTVHmvgu-py3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/pypoetry/virtualenvs/schema-transformations-hTVHmvgu-py3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "[...]/pypoetry/virtualenvs/schema-transformations-hTVHmvgu-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/pypoetry/virtualenvs/schema-transformations-hTVHmvgu-py3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/pypoetry/virtualenvs/schema-transformations-hTVHmvgu-py3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/pypoetry/virtualenvs/schema-transformations-hTVHmvgu-py3.11/lib/python3.11/site-packages/linkml_map/cli/cli.py", line 97, in map_data
    tr_obj = tr.map_object(input_obj, source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/pypoetry/virtualenvs/schema-transformations-hTVHmvgu-py3.11/lib/python3.11/site-packages/linkml_map/transformer/object_transformer.py", line 204, in map_object
    v = self._perform_unit_conversion(slot_derivation, source_obj, sv, source_type)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/pypoetry/virtualenvs/schema-transformations-hTVHmvgu-py3.11/lib/python3.11/site-packages/linkml_map/transformer/object_transformer.py", line 321, in _perform_unit_conversion
    if slot.unit.ucum_code:
       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'ucum_code'
```

**Comment by Silvanoc** [comment]
Closing because it is not a bug, but a lack of information in the tutorial. The specification of `unit` in `height_in_cm` was missing.

**Comment by Silvanoc** [comment]
https://github.com/linkml/linkml-map/pull/34 should helps others avoid stumbling upon the same stone
