### ISSUE TITLE
gen-project: AttributeError on a malformed config AND includes/excludes as string silently skips generators AND minor bugs

### ISSUE THREAD

**Issue by noelmcloughlin** [linkml/linkml#3858]
**Describe the bug**

During PR #3781 testing various bugs were found during testing::

- `gen-project` skips validation on the YAML it is handed. If `--config-file` or `-A/--generator-arguments` parses as valid YAML but are unexpected mappings, the value is stored and blows up later on attribute access. The user gets unhandled `AttributeError` traceback,  instead of helpful output like this ...
```bash
Error: --config-file: expected a YAML mapping at 'generator_args', found str
```

-   `generate()` does `gen_name in config.excludes.` With a list that's membership (good); with a string it's substring matching (bad here), and jsonld is a substring of jsonldcontext. So excluding one generator silently excludes another

- Validation is CLI-only.  ProjectGenerator.generate() is public and used programmatically and still dies on bad ProjectCofiguration:

`AttributeError**: 'str' object has no attribute 'get'`

- Arg -A silently replaces `--config-file`'s `generator_args` rather than merging. Undocumented behavior.

**Version of LinkML you are using**
1.11.1

**Please provide a schema (and if applicable, a data file) that replicates the issue**

```bash
cat > /tmp/myschema.yaml <<'EOF'
id: https://example.org/test
name: test
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string
classes:
  Thing:
    slots:
      - name
slots:
  name:
EOF
```

Test: top level isn't a mapping:
```bash
printf 'justastring\n' > /tmp/config.yaml
uv run gen-project --config-file /tmp/config.yaml -d out /tmp/myschema.yaml

  File ".../linkml/generators/projectgen.py", line 233, in cli
    for k, v in yaml.safe_load(config_file).items():
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'items'
```

Test: --config-file `generator_args` isn't a mapping:
```bash
printf 'generator_args: java.package=org.example.model\n' > /tmp/config.yaml
uv run gen-project --config-file /tmp/config.yaml -d out /tmp/myschema.yaml

  File ".../linkml/generators/projectgen.py", line 122, in generate
    **config.generator_args.get(gen_name, {}),
      ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
```

Test: `-A` is not a mapping
```bash
uv run gen-project -A 'notamapping' -d out /tmp/myschema.yaml

AttributeError: 'str' object has no attribute 'get'
```
.. crashing deep inside `generate()` with no cause signal

Test: excludes/includes as a string silently generates the wrong artifacts
```bash
printf 'excludes: jsonldcontext\n' > /tmp/config.yaml
gen-project --config-file /tmp/config.yaml -d out /tmp/schema.yaml  # exit 0

ls out/jsonld/     # empty/gone - loop matched 'jsonld' generator to 'jsonldcontext' string)
```
