### ISSUE TITLE
rdflib v7 introduces breaking changes

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1567]
When we migrated from v5 to v6 (https://github.com/linkml/linkml/issues/291) we left the `.decode()`s in place; while no longer necessary, they worked in both 5 and 6.

v7 seems to drop support for this altogether, which introduces breaking changes in owlgen

`AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?`

The quick fix is for schema repos to pin to 6. but we should change the code to remove the decodes - we have already dropped support for rdflib v5 anyway

**Comment by sneakers-the-rat** [comment]
is this literally as simple as removing the `decode` calls? because i'd be happy to make that PR because this is breaking https://github.com/linkml/linkml-project-cookiecutter

**Comment by cmungall** [comment]
yes, that is all that is required, and yes, most welcome!
