### PR TITLE
fix(projectgen): validate yaml config properly and merge generator_args with cli args

### LINKED ISSUE #3858: gen-project: AttributeError on a malformed config AND includes/excludes as string silently skips generators AND minor bugs
**Describe the bug**

During PR #3781 testing various bugs were found during testing::

- `gen-project` skips validation on the YAML it is handed. If `--config-file` or `-A/--generator-arguments` parses as valid YAML but are unexpected mappings, the value is stored and blows up later on attribute access. The user gets unhandled `AttributeError` traceback,  instead of helpful output like this ...
```bash
Error: --config-file: expected a YAML mapping at 'generator_args', found str
```

-   `generate()` does `gen_name in config.excludes.` With a list that's membership (good); with a string it's substring matching (bad here), and jsonld is a substring of jsonldcontext. So excluding one generator silently excludes another

- Validation is CLI-only.  ProjectGenerator.generate() is public and used programmatically and still dies on bad ProjectCofiguration:

`AttributeError**: 'str' object has no attribute 'get'`

- Arg -A silently replaces `--config-file`'s `generator_args` rather than merging. Undocumented behavior.

**Version of LinkML you are using**
1.11.1

**Please provide a schema (and if applicable, a data file) that replicates the issue**

```bash
cat > /tmp/myschema.yaml <<'EOF'
id: https://example.org/test
name: test
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string
classes:
  Thing:
    slots:
      - name
slots:
  name:
EOF
```

Test: top level isn't a mapping:
```bash
printf 'justastring\n' > /tmp/config.yaml
uv run gen-project --config-file /tmp/config.yaml -d out /tmp/myschema.yaml

  File ".../linkml/generators/projectgen.py", line 233, in cli
    for k, v in yaml.safe_load(config_file).items():
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'items'
```

Test: --config-file `generator_args` isn't a mapping:
```bash
printf 'generator_args: java.package=org.example.model\n' > /tmp/config.yaml
uv run gen-project --config-file /tmp/config.yaml -d out /tmp/myschema.yaml

  File ".../linkml/generators/projectgen.py", line 122, in generate
    **config.generator_args.get(gen_name, {}),
      ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
```

Test: `-A` is not a mapping
```bash
uv run gen-project -A 'notamapping' -d out /tmp/myschema.yaml

AttributeError: 'str' object has no attribute 'get'
```
.. crashing deep inside `generate()` with no cause signal

Test: excludes/includes as a string silently generates the wrong artifacts
```bash
printf 'excludes: jsonldcontext\n' > /tmp/config.yaml
gen-project --config-file /tmp/config.yaml -d out /tmp/schema.yaml  # exit 0

ls out/jsonld/     # empty/gone - loop matched 'jsonld' generator to 'jsonldcontext' string)
```

### PR DESCRIPTION
**Pull request by noelmcloughlin**
## Summary

Fixes #3858

- Various bugs found in projectgen configuration management
- **Allow merging configuration supplied by CLI (`-A` wins) and configuration file (`-C config.yaml`)**
- fix test gap: empty config file causing crashes was inadvertently  fixed (missing test case)

Starts addressing https://github.com/linkml/linkml/issues/3972 following PR comment.

## How was this tested?

expanded tests

## Areas of uncertainty

- merging generator_args with cli args (-A) is new behavior but old behavior was silent skip / undocumented

## Checklist

- [x] My code follows the [contributor guidelines](https://linkml.io/linkml/maintainers/contributing.html)
- [x] I have added tests that prove my fix/feature works
- [x] Existing tests pass locally with my changes

## AI Assistance
LLM assisted

### CODE REVIEW

File: packages/linkml/src/linkml/generators/projectgen.py [hunk 1]
```diff
@@ -70,6 +70,135 @@ def get_local_imports(schema_path: Path, dir: Path):
...
+
+    :param value: YAML text, or an open file to read it from.
+    :param source: Where it came from, e.g. ``"--config-file"``.
+    :return: Whatever the YAML held.
+    :raises ValueError: if the YAML is malformed.
+    """
+    try:
+        return yaml.safe_load(value)
+    except yaml.YAMLError as e:
+        raise ValueError(f"{source} is not valid YAML: {e}") from e
```
Comment (kevinschaper) [inline packages/linkml/src/linkml/generators/projectgen.py:84]: This validation now exists twice. #3781 landed `_config_mapping` / `read_generator_config` in `linkml/utils/generator.py` on 2026-09-01 — after this branch's base — and `gen-java` / `gen-golang` already use it against the *same* `config.yaml`. This PR adds a second implementation here.

They have already drifted on the error text for the same malformed file:

```
gen-java     ->  Error: --config-file: could not parse as YAML: ...
gen-project  ->  Error: --config-file is not valid YAML: ...
```

and after the (mandatory) rebase, `generate()` would raise `ValueError` from this path while main's shared helper raises `click.UsageError` for the same class of problem — two exception types one caller has to catch.

Since you have to rebase anyway, worth folding this into the shared helper rather than carrying a parallel implementation. If `projectgen` needs something the shared one doesn't do, extending it there means `gen-java` and `gen-golang` get the same fix.

Not a criticism of the code — #3781 simply landed underneath you.

File: packages/linkml/src/linkml/generators/projectgen.py [hunk 2]
```diff
@@ -70,6 +70,135 @@ def get_local_imports(schema_path: Path, dir: Path):
...
+    :param value: Whatever was found at this point in the configuration.
+    :param where: Where that was, for the error message, e.g. ``"'excludes'"``.
+    :param source: The option it came from, e.g. ``"--config-file"``.
+    :return: The list of names, empty if nothing was configured.
+    :raises ValueError: if the value is not a list of names, nor empty.
+    """
+    if value is None:
+        return []
+    if not isinstance(value, list):
+        raise ValueError(f"{source}: expected a YAML list of generator names at {where}, found {type(value).__name__}")
```
Comment (kevinschaper) [inline packages/linkml/src/linkml/generators/projectgen.py:145]: The docstring explains the reasoning well, and the bug is real. I'd argue coercion resolves it better than rejection, though.

The failure mode you document is substring matching:

```
bare 'jsonldcontext'       -> skips ['jsonld', 'jsonldcontext']   # the bug
coerced ['jsonldcontext']  -> skips ['jsonldcontext']             # correct
bare 'shex'                -> skips ['shex']                      # already correct today
```

Coercing `str` -> `[str]` fixes the `jsonld`/`jsonldcontext` collision *properly*, rather than outlawing the syntax it happened to surface in. And it matters because the bare form works correctly today for every generator name that isn't a prefix of another — which is all of them except that one pair. I verified `excludes: shex` on main: exit 0, shex correctly skipped. Rejecting it turns a working config into `exit 2` with no deprecation period.

```suggestion
    if value is None:
        return []
    if isinstance(value, str):
        # A bare string is accepted as a one-item list. Treating it as a list
        # matters: ``gen_name in "jsonldcontext"`` is a substring test, so a
        # bare string would wrongly exclude ``jsonld`` as well.
        return [value]
    if not isinstance(value, list):
        raise ValueError(f"{source}: expected a YAML list of generator names at {where}, found {type(value).__name__}")
```

That flips the `excludes-string` / `includes-string` test params from "errors" to "excludes exactly one", which is the behaviour worth pinning.

If you'd rather keep the rejection — defensible, the form is undocumented and fail-fast is the house style — then it needs a changelog entry, because what a user sees on upgrade is a hard error on a config that worked yesterday.

**Review by kevinschaper — CHANGES_REQUESTED** [review]
I added a few claude generated inline comments

File: packages/linkml/src/linkml/generators/projectgen.py (hunk 1 above)
Comment (noelmcloughlin) [reply packages/linkml/src/linkml/generators/projectgen.py]: Fixed by new commit. I forgot about this PR and started work on Issue #3972 for better cross-generator solution and proposed a 1st PR https://github.com/linkml/linkml/issues/3972 - so I borrowed code from there to address this concern in a forward-compatible way - we leave javagen/golangto be addressed in the other PR.

File: packages/linkml/src/linkml/generators/projectgen.py (hunk 2 above)
Comment (noelmcloughlin) [reply packages/linkml/src/linkml/generators/projectgen.py:157]: Added coercing commit.

**Review by kevinschaper — APPROVED** [review]
thanks @noelmcloughlin!
