### ISSUE TITLE
LinkML does not work with Python 3.10

### ISSUE THREAD

**Issue by sujaypatil96** [linkml/linkml#715]
Try running any of the tests from the current test suite using Python 3.10. You will see an error along the lines of the below traceback:

```
 ➜  linkml git:(spatil/add-materialize-patterns) ✗ pipenv run python3.10 -m unittest tests/test_generators/test_excelgen.py
Traceback (most recent call last):
  File "/Users/sujaypatil/.pyenv/versions/3.10.0/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/sujaypatil/.pyenv/versions/3.10.0/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/sujaypatil/.pyenv/versions/3.10.0/lib/python3.10/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/Users/sujaypatil/.pyenv/versions/3.10.0/lib/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/Users/sujaypatil/.pyenv/versions/3.10.0/lib/python3.10/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/Users/sujaypatil/.pyenv/versions/3.10.0/lib/python3.10/unittest/main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "/Users/sujaypatil/.pyenv/versions/3.10.0/lib/python3.10/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/sujaypatil/.pyenv/versions/3.10.0/lib/python3.10/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/sujaypatil/.pyenv/versions/3.10.0/lib/python3.10/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/sujaypatil/Desktop/linkml/tests/__init__.py", line 6, in <module>
    from tests.utils.test_environment import MismatchAction
  File "/Users/sujaypatil/Desktop/linkml/tests/utils/test_environment.py", line 14, in <module>
    from linkml_runtime.linkml_model import linkml_files
  File "/Users/sujaypatil/.local/share/virtualenvs/linkml-oMZ7enEf/lib/python3.10/site-packages/linkml_runtime/__init__.py", line 2, in <module>
    from linkml_runtime.utils.schemaview import SchemaView
  File "/Users/sujaypatil/.local/share/virtualenvs/linkml-oMZ7enEf/lib/python3.10/site-packages/linkml_runtime/utils/schemaview.py", line 12, in <module>
    from linkml_runtime.linkml_model.meta import *
  File "/Users/sujaypatil/.local/share/virtualenvs/linkml-oMZ7enEf/lib/python3.10/site-packages/linkml_runtime/linkml_model/__init__.py", line 3, in <module>
    from .extensions import Extension, Extensible
  File "/Users/sujaypatil/.local/share/virtualenvs/linkml-oMZ7enEf/lib/python3.10/site-packages/linkml_runtime/linkml_model/extensions.py", line 46, in <module>
    class Extension(YAMLRoot):
  File "/Users/sujaypatil/.pyenv/versions/3.10.0/lib/python3.10/dataclasses.py", line 1178, in dataclass
    return wrap(cls)
  File "/Users/sujaypatil/.pyenv/versions/3.10.0/lib/python3.10/dataclasses.py", line 1169, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
  File "/Users/sujaypatil/.pyenv/versions/3.10.0/lib/python3.10/dataclasses.py", line 1019, in _process_class
    _init_fn(all_init_fields,
TypeError: dataclasses_init_fn_with_kwargs() missing 1 required positional argument: 'slots'
```

We need to correct the implementation for `dataclasses_init_fn_with_kwargs()` so that linkml can work with Python 3.10 as well. I believe a similar correction was made on the linkml-runtime repo as well?

**Comment by cmungall** [comment]
I thought @hsolbrig addressed this with https://github.com/linkml/linkml-runtime/issues/73

> We need to correct the implementation for dataclasses_init_fn_with_kwargs() so that linkml can work with Python 3.10 as well. I believe a similar correction was made on the linkml-runtime repo as well?

@sujaypatil96 -- I think we only need to make the change in one place, that is the runtime repo?

**Comment by cmungall** [comment]
It looks like runtime is tested against 3.10

https://github.com/linkml/linkml-runtime/blob/main/.github/workflows/main.yaml

Are you completely sure your test above uses the latest runtime? I will try changing the actions cfg in this repo to see if it reproduces..

**Comment by sujaypatil96** [comment]
@cmungall: yup, I just checked my Pipfile.lock again to see what version of linkml-runtime was running on there, and it's v1.2.7 which is the latest version.

**Comment by sujaypatil96** [comment]
Oh wow, the experimental PR #718 that you have seems to be going through properly. So strange. I guess it's some inconsistency with pyenv that I'm missing then.

**Comment by sujaypatil96** [comment]
Close this issue in favour of the test in PR #718.
