### ISSUE TITLE
schemasheets tools not working in MIxS repo because "cannot import name 're' from 'linkml_runtime.utils.schemaview'"

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#2828]
https://github.com/GenomicsStandardsConsortium/mixs

```shell
make assets/class_summary_results.tsv
```

does

```shell
poetry run linkml2sheets \
                --schema src/mixs/schema/mixs.yaml \
                 --output assets/class_summary_results.tsv assets/class_summary_template.tsv
```

which says

> ```
> Traceback (most recent call last):
>   File "/Users/MAM/Documents/gitrepos/compare-mixs/main/mixs/.venv/bin/linkml2sheets", line 5, in <module>
>     from schemasheets.schema_exporter import export_schema
>   File "/Users/MAM/Documents/gitrepos/compare-mixs/main/mixs/.venv/lib/python3.11/site-packages/schemasheets/schema_exporter.py", line 16, in <module>
>     from schemasheets.schemamaker import SchemaMaker
>   File "/Users/MAM/Documents/gitrepos/compare-mixs/main/mixs/.venv/lib/python3.11/site-packages/schemasheets/schemamaker.py", line 20, in <module>
>     from linkml_runtime.utils.schemaview import SchemaView, re
> ImportError: cannot import name 're' from 'linkml_runtime.utils.schemaview' (/Users/MAM/Documents/gitrepos/compare-mixs/main/mixs/.venv/lib/python3.11/site-packages/linkml_runtime/utils/schemaview.py)
> make: *** [assets/class_summary_results.tsv] Error 1
> ```

**Comment by turbomam** [comment]
- linkml version      : 1.9.1                              
- linkml-runtime version      : 1.9.4                                                                  
- schemasheets version      : 0.1.24

**Comment by turbomam** [comment]
Problem Analysis

  1. Root Cause: schemasheets package has a bug in schemamaker.py line 20:
  from linkml_runtime.utils.schemaview import SchemaView, re
  1. This incorrectly tries to import Python's re module from schemaview instead of importing it separately.
  2. Current Versions:
    - schemasheets: 0.1.24
    - linkml-runtime: 1.9.4
  3. The Import Works Separately:
    - from linkml_runtime.utils.schemaview import SchemaView ✅
    - import re ✅

**Comment by turbomam** [comment]
but 0.4.0 is the schemasheets latest

**Comment by turbomam** [comment]
over-constrained `schemasheets` in `pyproject.toml`'s `tool.poetry.group.dev.dependencies`

probably not a LinkML bug
